version: '3.8'

services:
  model:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=microsoft/phi-3
      - MODEL_REVISION=latest
      - MAX_SEQUENCE_LENGTH=2048
      - DEFAULT_TEMPERATURE=0.7
      - PORT=8000
      - HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
